# Emergency Procedures {-}



## Downed Drone Recovery Checklist {-}

- Verify that all emergency response has concluded
- Verify that the downed drone will not cause collateral damage through a fire or fluid leak
- Shutdown the Drone and all equipment
    
    - Send power-down command to drone
    - Power-down control and communications equipment

- Secure the project site. Stow all equipment and supplies not required for the aircraft recovery effort
- Is the drone on public or private property?
 
    - Private - Contact the land owner before continuing with the recovery
    - Public - Continue with recovery
 
- Can the drone be accessed safely?
 
    - No - Contact your (ref:DLA)
    - Yes - Continue with recovery

- Access the Drone
 
    - Power down the drone
    - Remove the fuel source
 
        - Remove batteries
        - Close liquid fuel valve

- Document the crash

    - Take photographs, make notes and sketches as needed

- Remove the Drone
 
    - Clean all debris from the site
