# (PART\*) Organization {-}



# Bylaws {-}

The (ref:UCCBOlong) 

## Article 1 - Name and Purpose {-}

**Section 1: *Name*:** The name of this organization is (ref:UCCBOlong). It is ....

**Section 2: *Purpose*:** (ref:UCCBOlong) is organized to further aeronautical knowledge and skills through education and research, and to provide opportunities for members of the University of California to develop and utilize drones.

## Article 2 - Membership {-}

**Section 1: *Eligibility for membership*:** The (ref:UCCBOlong) is a membership-based organization that is open to any affiliate of the University of California.

**Section 2: *Application for membership*:** Prospective members may sign up for membership by subscribing to the (ref:listserv).

**Section 3: *Resignation of membership*:** Any member may resign by unsubscribing to the (ref:listserv)

## Article 3 - Management {-}

**Section 1: *Oversight*:** The (ref:UCCBOlong) is managed by the (ref:UCCOElong) under the direction of (ref:SDA) and the (ref:AB).

**Section 2: *Working groups*:** The (ref:UCCBOlong) may establish special purpose committees to address specific needs of the (ref:UCCBOlong).

**Section 3: *Working group membership*:** Membership in a working group will be solicited over the (ref:listserv) and appointed by the (ref:SDA). Selection consideration includes prior experience, availability and the needs of the working group.


## Article - Grievance Procedure {-}
The grievance procedure provides a mechanism to enforce existing safety rules by providing a progressive disciplinary system when needed. Most complaints can be resolved informally and should be rectified with training and education.  If a complaint is serious or cannot be resolved informally, the matter should be referred to the (ref:AB) for its consideration by means of a Grievance Form to be filled out and turned into the Systemwide Designated UAS Authority. At least one witness is required to sign the Grievance Form.

The Systemwide Designated UAS Authority and the UC UAS Advisory Board shall use its judgment in carrying out action.

### First Violation
Viewpoints of both complainants and accused will be considered. Complainant’s name will be disclosed. A verbal reprimand will be given to the accused by the Safety or Faculty lead, and this will be recorded in the campus UAS records.

### Repeat Violation 
Repeat offences, or blatant disregard for UC UAS policy or campus safety, shall be reported to the campus for disciplinary review under the appropriate policy.

### Retailation
Any member receiving a Grievance, who directs any retaliation action against the person filing said grievance, will be subject to immediate expulsion from the program. This is to include threats, intimidation, physical harm, intentional equipment damage, or any other action deemed to be retaliatory.


# Campus Management {-}
The local division of the (ref:UCCBO) is managed through each campus.  


## Requirements for Participation {-}

A campus that wishes to participate within the (ref:UCCBO) must form a group comprising of at least:

    - Safety Lead
    - Faculty Lead

## Safety Lead {-}

The Safety Lead reports UAS activity to the (ref:UCCOE).  A Campus (ref:DLA) may concurrently act as the Safety Lead for the (ref:UCCBO).

## Faculty Lead {-}

## Site Management {-}
The Campus is responsible for managing fixed-flying site activity and site coordination across the campus. Flying sites must be developed in collaboration with the facility manager and other space users.


# Membership {-}

The (ref:UCCBOlong) is a membership-based organization to further aeronautical knowledge and skills through education and research, and to provide opportunities for members of the University of California to develop and utilize drones.


## Joining {-}

Membership in the (ref:UCCBOlong) is available for all UC affiliates. Interested persons may sign up for membership by subscribing to the (ref:listserv).  The (ref:UCCBO) does not require dues or a minimal level of participation.

## Requirements for Membership {-}

Members of the (ref:UCCBO) must be an affiliate of the University of California with a UC email account. 

## Membership Levels {-}
The (ref:UCCBO) has three membership levels

1. General Member
2. Advanced Member
3. Flight Instructor

### General Member {-}

Upon signing up for the (ref:UCCBO), an applicant is regarded as a `General Member.' This classification signifies an interest in participating and supporting in model aviation and drones.  No experience or minimal level of participation is required for general membership.

General Members are expected to abide by the general safety guidelines when operating under the (ref:UCCBO).  


### Advanced Member {-}

An Advanced Member is an member of the (ref:UCCBO) that has completed the supplemental training for drone operations within the University of California.  It is expected that an Advanced Member has either a (ref:TRUSTcert) or a (ref:RPC), and an appropriate level of flight experience.

Advanced members are eligible to take additional specialty training to support advanced flight operations in accordance to their respective special-use guidelines.  Advanced flight operations include first person view operations, operations of aircraft over 55 lbs, and other operations that require additional considerations.


### Flight Instructor {-}

A Flight Instructor is a member of the (ref:UCCBO) that has completed both the supplemental training for drone operations and the supplemental training for flight instruction.  It is expected that an Advanced Member has either a (ref:TRUSTcert) or a (ref:RPC), an appropriate level of flight experience, and teaching experience.

It is recommended that any person responsible for training a new pilot should reach this level of membership.


